name: Java CI with Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload a Build Target
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "CatSero-Artifact"
          path: target/